# Travis CI configuration file for piqd project. Installs Python, Django, and 
# MySQL, then instructs Django to run unit tests

language: python

python:
  - "3.6"

services: 
  - mysql

env:
  - DJANGO=1.11 DB=sqlite

install:
  - pip3 install -r requirements.txt

script:
  - python3 piqd_site/manage.py test

